// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkJWpQZFSiFiYkDiaDMjMPTbLHa2I2BD4',
    appId: '1:604482576544:web:d75301bd5ea6839e1729c5',
    messagingSenderId: '604482576544',
    projectId: 'messagesboard-1c322',
    authDomain: 'messagesboard-1c322.firebaseapp.com',
    storageBucket: 'messagesboard-1c322.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGSEcDe6rpyCaZwlBLhMTMdGwjpPeXYU0',
    appId: '1:604482576544:android:06144fe1763a6bc71729c5',
    messagingSenderId: '604482576544',
    projectId: 'messagesboard-1c322',
    storageBucket: 'messagesboard-1c322.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEraVx00d2btL6gya7pjdgSiVDIlnyJN0',
    appId: '1:604482576544:ios:b989ec4e942da2d71729c5',
    messagingSenderId: '604482576544',
    projectId: 'messagesboard-1c322',
    storageBucket: 'messagesboard-1c322.appspot.com',
    iosClientId: '604482576544-341j7k52fp3hplrl2r5l9mnme9njigv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.profile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEraVx00d2btL6gya7pjdgSiVDIlnyJN0',
    appId: '1:604482576544:ios:b989ec4e942da2d71729c5',
    messagingSenderId: '604482576544',
    projectId: 'messagesboard-1c322',
    storageBucket: 'messagesboard-1c322.appspot.com',
    iosClientId: '604482576544-341j7k52fp3hplrl2r5l9mnme9njigv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.profile',
  );
}
